package com.inmapper.ws.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.inmapper.ws.model.RoomLocation;

/**
 * Room Map Point repository. The implementation of this class will be automatically generated by
 * Spring Data framework.
 * 
 * @author trein
 */
@Repository
public interface RoomLocationRepository extends JpaRepository<RoomLocation, Long> {
    
    List<RoomLocation> findAllByRoomId(String roomId);
    
}
